name: "ci"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:

  spec:
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - '3.2'
    name: "spec (ruby ${{ matrix.ruby_version }})"
    uses: "puppetlabs/cat-github-actions/.github/workflows/gem_ci.yml@main"
    secrets: "inherit"
    with:
      rake_task: "spec:coverage"
      ruby_version: ${{ matrix.ruby_version }}

